#!/bin/sh

KERNEL_CONFIG=./.config

if [[ ! -f "${KERNEL_CONFIG}" ]]; then
	echo "Current working directory needs to be the one with a kernel sources!" >&2
	exit 1
fi

## check if root is mounted from LVM/Luks/etc.
ROOT_DEV_FILE=`grep '^[^ ]*\s/\s' /proc/mounts | tail -1 | sed 's|^[^ ]*/\([^/ ]*\) .*$|\1|'`
OPTS="$@ all"
grep -q "^[^ ]*${ROOT_DEV_FILE}\\s/\\sbtrfs\\s" /proc/mounts && OPTS="--btrfs ${OPTS}" || OPTS="--no-btrfs ${OPTS}"
if lvdisplay -c "/dev/mapper/${ROOT_DEV_FILE}" 2>/dev/null 1>&2; then
	OPTS="--lvm ${OPTS}"
	# if the root is in LVM, find its PV and use it as the root device (e.g., to check its encryption etc. later)
	ROOT_VG=$(lvdisplay -c "/dev/mapper/${ROOT_DEV_FILE}" 2>/dev/null | cut -d : -f 2)
	ROOT_PV=$(pvdisplay -c 2>/dev/null | sed "s|\\s*\\([^\\s:]*\\):${ROOT_VG}:.*\$|\\1|") #"
	[[ -n "${ROOT_PV}" ]] && ROOT_DEV_FILE="${ROOT_PV}"
else
	OPTS="--no-lvm ${OPTS}"
fi
dmsetup status "${ROOT_DEV_FILE}" | grep -q '\scrypt\s' && OPTS="--luks ${OPTS}" || OPTS="--no-luks ${OPTS}"

## extra modules
MODULES_EXTRA="serio i8042 atkbd" \
exec genkernel "--kernel-config=${KERNEL_CONFIG}" ${OPTS}
