#!/bin/sh

# update "imported" overlay by a script
IMPDIR="$(portageq get_repo_path / imported)"
IMPSCR="${IMPDIR}/update.sh"
[[ -d "${IMPDIR}" && -x "${IMPSCR}" ]] && "${IMPSCR}"

# update gentoo portage and overlays managed by repositories-configuration in repos.conf.d (see portage(5))
emerge --sync

# update eix database
mv -v /var/cache/eix/portage.eix /var/cache/eix/previous.eix
eix-update
exec eix-diff
