#!/bin/sh

KERNEL_CONFIG=./.config

if [[ ! -f "${KERNEL_CONFIG}" ]]; then
	echo "Current working directory needs to be the one with a kernel sources!" >&2
	exit 1
fi

## check if root is mounted by device mapper (i.e. at LVM/Luks)
if grep -q '^/dev/mapper/[^ ]\{1,\}\s\{1,\}/\s' /etc/fstab; then
	exec genkernel "--kernel-config=${KERNEL_CONFIG}" --luks --lvm all
else
	exec genkernel "--kernel-config=${KERNEL_CONFIG}" --no-luks --no-lvm all
fi
