#!/sbin/openrc-run

NAME="cassandra-{SLOT}"
DESC="Apache Cassandra v{PV}"
PIDFILE="/var/run/${NAME}/${NAME}.pid"

_CASSANDRA_DIR="/opt/${NAME}"

DAEMON="${_CASSANDRA_DIR}/bin/cassandra"
DAEMON_OPTS="-p ${PIDFILE}"
USER="cassandra"

source "${_CASSANDRA_DIR}/bin/cassandra.in.sh"
source "${_CASSANDRA_DIR}/conf/cassandra-env.sh"

start_pre() {
	checkpath -d -m 0755 -o ${USER}:${USER} $(dirname "${PIDFILE}")
}

start() {
	ebegin "Starting ${DESC}"
	start-stop-daemon \
		--start \
		--user "${USER}" \
		--exec "${DAEMON}" \
		--quiet \
		--pidfile "${PIDFILE}" \
		--test >/dev/null || eend 1
	start-stop-daemon \
		--start \
		--user "${USER}" \
		--exec "${DAEMON}" \
		--background \
		--pidfile "${PIDFILE}" \
		-- ${DAEMON_OPTS} >/dev/null
	eend $?
}

stop() {
	ebegin "Stopping ${DESC}"
	start-stop-daemon --stop --quiet --oknodo --pidfile "${PIDFILE}"
	eend $?
}

restart() {
	ebegin "Restarting cassandra"
	start-stop-daemon \
		--stop \
		--quiet \
		--oknodo \
		--retry TERM/30/KILL/5 > /dev/null || eend 1
	start-stop-daemon \
		--start \
		--quiet \
		--pidfile "${PIDFILE}" \
		--chuid "${USER}" \
		--exec "${DAEMON}" \
		-- ${DAEMON_OPTS} > /dev/null
	eend $?
}
