#!/bin/bash

IN="${1:-contacts.csv}"

if [ ! -f "${IN}" ]; then
	echo "Cannot open file '${IN}' with esmska's contacts!" >&2
	echo >&2
	echo "Usage:	${0} [contacts.csv]" >&2
	echo >&2
	echo "Detect gateways for all contacts in a file." >&2
	exit 2
fi

cat "${IN}" | while read L; do
	if [ "${L:0:1}" != "#" ]; then
		NAME=$(echo "${L}" | cut -d ',' -f 1)
		NUMBER=$(echo "${L}" | cut -d ',' -f 2)
		GW_ORIG=$(echo "${L}" | cut -d ',' -f 3-)
		GW_DETECTED=$(esmska-gw-for-number "${NUMBER}")
		if [ "${GW_ORIG}" != "${GW_DETECTED}" ]; then
			echo "#${L}" >&2
		fi
		echo "${NAME},${NUMBER},${GW_DETECTED}" >&1
	else
		echo "${L}" >&1
	fi
done